### PR TITLE
feat: include `@rspack/react-refresh-plugin` with Re.Pack

### LINKED ISSUE #804: repack v5 by webpack  need to install rspack
### Describe the bug

i don't use rspack but when migrate to v5 i got this `Error: Cannot find module '@rspack/core'` and `Error: Cannot find module '@rspack/plugin-react-refresh'`

### System Info

```shell
npx react-native info
error Failed to load configuration of your project.
Error: Cannot find module '@rspack/core'
Require stack:
```

### Re.Pack Version

5.0.0-rc.2

### Reproduction

use webpack

### Steps to reproduce

react-native webpack-start

### PR DESCRIPTION
**Pull request by jbroma**
### Summary

Closes #804 

`@rspack/react-refresh-plugin` is now included in Re.Pack instead of being a peer dependcy since it's used in both webpack and rspack variants

### Test plan

n/a

### CODE REVIEW

**Comment by hosseinmd** [comment]
also `@rspack/core` should be installed

**Comment by jbroma** [comment]
> also `@rspack/core` should be installed

there shouldn't be a need to do that, can you show me an example where that's the problem?

**Comment by jbroma** [comment]
just tested on fresh project with webpack - there are no errors related to `@rspack/core` missing 🤷

**Review by thymikee — APPROVED** [review]
