### ISSUE TITLE
How to locate cause of Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by krzysztofzaluski** [callstack/repack#654]
I've noticed that if there is an error in the component code or some configuration file, such as missing a library in `package.json` and if I'm using it in the component or config file, then it always throws me an error:

```
[Error: ENOENT: no such file or directory, open '/Users/krzysztofzaluski/Documents/react-native/Project/build/generated/android/index.bundle'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/krzysztofzaluski/Documents/react-native/Project/build/generated/android/index.bundle'
}
```

so the problem is that the error message doesn't say anything specific that could help to locate the real issue, like the code line where the old removed import is still present, etc.

are there some ways how to track such a cases and locate such a files with issues?

**Comment by krzysztofzaluski** [comment]
to complete the question I would like to add that my solution e.g. for missing imports is to scan the project with eslint with tsc but maybe there are still some cases where this error `Error: ENOENT: no such file or directory ` can appear and maybe there is a chance for the console to display a more precise problem?

**Comment by jbroma** [comment]
Hi @krzysztofzaluski,

thanks for pinpointing this, we're not reporting compilation errors when running the dev server (as in metro, which display an LogBox error for that), so this would need to be implemented to spot this early on. 

When bundling for production this is most likely visible in the output - can you confirm this is the case?

**Comment by aw-capgemini** [comment]
Hi @jbroma I'm encountering the same issue after upgrading from repack v3 to v4  when bundling for production

### Description
I encountered an error while running the `pnpm bundle:ios` command using Repack. The error message indicates that a required file is missing.

### Error Message
[Error: ENOENT: no such file or directory, open '/Users/cgemployee/Projects/rahul/Digico/packages/host/build/generated/ios/index.bundle'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/Users/cgemployee/Projects/rahul/Digico/packages/host/build/generated/ios/index.bundle'
}
ELIFECYCLE  Command failed with exit code 2.


### Steps to Reproduce
1. Run the command `pnpm bundle:ios`
2. Observe the error message

### Expected Behavior
The bundling process should complete successfully and generate the `index.bundle` file.

### Environment
- **Repack Version**: v4
- **React Native Version**: 0.72.0
- **Node Version**: 19
- **Operating System**: macOS

### Additional Context
I have verified that the directory structure exists and that the entry file (`index.js`) is correctly specified. I have also tried running clean commands and manually creating the missing directories, but the issue persists.

**Comment by krzysztofzaluski** [comment]
hey @jbroma 
I'm bundling the app using this command, where `--dev` flag is set to  `false`:

`react-native webpack-bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

do you mean some other bundling type?

**Comment by krzysztofzaluski** [comment]
hey, in my case this version helped, when bundling the application it shows the more specific error message in the console
thanks @jbroma

**Comment by jbroma** [comment]
@krzysztofzaluski glad to hear that! 

I'll close this issue - if anybody faces a similar issue like this please open a new issue with the new bug issue template
