### ISSUE TITLE
repack v5 by webpack  need to install rspack

### ISSUE THREAD

**Issue by hosseinmd** [callstack/repack#804]
### Describe the bug

i don't use rspack but when migrate to v5 i got this `Error: Cannot find module '@rspack/core'` and `Error: Cannot find module '@rspack/plugin-react-refresh'`

### System Info

```shell
npx react-native info
error Failed to load configuration of your project.
Error: Cannot find module '@rspack/core'
Require stack:
```

### Re.Pack Version

5.0.0-rc.2

### Reproduction

use webpack

### Steps to reproduce

react-native webpack-start

**Comment by hosseinmd** [comment]
It was my mistake.

**Comment by hosseinmd** [comment]
Although I don't use rspack, I need to install it,

**Comment by jbroma** [comment]
You should only need to install the refresh plugin and not the rspack itself, was that the issue?

**Comment by hosseinmd** [comment]
IMO, it should be added by repack dependencies or don't force me to install

**Comment by hosseinmd** [comment]
It is an issue.

**Comment by jbroma** [comment]
> IMO, it should be added by repack dependencies or don't force me to install

hmm yeah, since it's used for both I guess we can include it and remove it from user-managed dependencies. It seems to be very stable too so the having it as a peer dep doesn't make much sense in this case.

**Comment by jbroma** [comment]
In the PR mentioned above I've added `@rspack/react-refresh-plugin` a direct dependency of repack so you won't need to install it. Can you please double check if your issue was only with `@rspack/react-refresh-plugin` missing? Thanks!
